### ISSUE TITLE
gunicorn command not found

### ISSUE THREAD

**Issue by pjockey** [sflems/led-board-manager#13]
followed the instructions on the github and when I run the command `gunicorn Capstone.wsgi -b 0:9002` I get bash error gunicorn command not found.

I watch it get installed. I'm in the `led-board-manager` folder.

**Comment by sflems** [comment]
Usually happens when I forget to startup the virtual env. Just to confirm have you fired it up like so:

```
pi@raspberrypi:~/led-board-manager $ source env/bin/activate
(env) pi@raspberrypi:~/led-board-manager
```
The (env) contains the app requirements 👍

**Comment by sflems** [comment]
It was also missing from the readme. My mistake! It has been added.

**Comment by pjockey** [comment]
Thanks, that did the trick.

Can you get it to work the Opera browser? getting a ```
Forbidden (403)
CSRF verification failed. Request aborted.
```

**Comment by sflems** [comment]
Can look into it now. Just curious, is this on login? (Or Form submission?)

**Comment by sflems** [comment]
Just tested on latest Opera, Chrome and Edge browsers with not issues. Im wondering if Opera is blocking cookies on the site. The CSRF method uses cookies to send the token with form submissions. Can you try adding your device IP to the allowed site cookies in Opera? You can find the instructions [here](https://help.opera.com/en/latest/web-preferences/#cookies).

**Comment by pjockey** [comment]
Thanks again.
One more thing, when adding the extra score boards, MLB, which json setup are you looking for? String, object?

**Comment by sflems** [comment]
The forms in admin and the 'Edit JSON' config forms on main site are looking for an object. You can simply copy and paste any old configs from file this way.

I'm planning on adding a better import/export feature in the future. Feel free to create another issue if you're looking for any specifics. Let me know if that answers your question!

**Comment by sflems** [comment]
Closing this as v2.0.1 has additions to readme to address issues. Thank you!

**Comment by sflems** [comment]
Just to confirm, is the `supervisor-daemon.conf` file present in the `led-scoreboard-directory` and could you post the contents?

Does a 
```sudo supervisorctl reread && sudo supervisorctl update all``` notify any changes/resync the activation? It's sounding like it hasn't been read by supervisor so that it will know where the processes are. 

If this doesn't work, could you paste the output of the supervisor log?

```
cat /var/log/supervisord.log
``
