### ISSUE TITLE
Edit JSON button does not work with empty/missing schema

### ISSUE THREAD

**Issue by pjockey** [sflems/led-board-manager#18]
Just ran the update process and when the website loads I get the error above. The Supervisor website loads and the boards attached it start up and function. 

```
[2021-06-12 12:42:16 -0600] [2793] [INFO] Booting worker with pid: 2793
[2021-06-12 12:42:46 -0600] [2457] [CRITICAL] WORKER TIMEOUT (pid:2793)
[2021-06-12 12:42:46 -0600] [2793] [INFO] Worker exiting (pid: 2793)
```

This is the output of the Terminal.

**Comment by sflems** [comment]
It's just the status monitor that's reporting the incorrect status correct?

If you activate a different profile does the status return? There has been a ghost issue where the GUI gets out of sync with supervisor and this usually resolves it. 

I'll look into changing the method that the GUI uses to check the status.

Let me know if that works as a hotfix for now, else we'll look at a few other culprits.

**Comment by pjockey** [comment]
I stopped the board from displaying the MLB from IP address:9001. Then start the led-board-manager at IP addres:9002 and received the attached image
<img width="1211" alt="Screen Shot 2021-06-13 at 10 30 43" src="https://user-images.githubusercontent.com/1387701/121815325-1c972d00-cc33-11eb-951e-e97560a793cb.png">

The screen shows the game today, still shows the supervisor not running, and nothing on the board.

The code below shows the output of the RPi.

```
pi@raspberrypi:~/led-board-manager $ source env/bin/activate && gunicorn Capstone.wsgi -b 192.168.1.175:9002
[2021-06-13 10:26:46 -0600] [16956] [INFO] Starting gunicorn 20.0.4
[2021-06-13 10:26:46 -0600] [16956] [INFO] Listening at: http://192.168.1.175:9002 (16956)
[2021-06-13 10:26:46 -0600] [16956] [INFO] Using worker: sync
[2021-06-13 10:26:46 -0600] [16959] [INFO] Booting worker with pid: 16959
```

**Comment by sflems** [comment]
From here, if you activate the MLB profile from the dashboard, the
supervisor status monitor should resync to the current process. Let me know
how that works out.

Sometimes this can get out of sync during a reboot or if you swap boards
outside of the dash (in Supervisor directly).

I'll look into including a change in how it checks the status the next
update.

**Comment by pjockey** [comment]
I changed the profiles back and forth between the NHL and MLB boards. It shows BoardType as being correct, but the supervisor does not start. Also, the page stays on the NHL board showing the game data. Nothing to the actual board.

**Comment by sflems** [comment]
Just to confirm, is the `supervisor-daemon.conf` file present in the `led-scoreboard-directory` and could you post the contents?

Does a 
```sudo supervisorctl reread && sudo supervisorctl update all``` notify any changes/resync the activation? It's sounding like it hasn't been read by supervisor so that it will know where the processes are. 

If this doesn't work, could you paste the output of the supervisor log?

```
cat /var/log/supervisord.log
```


Unfortunately just the NHL games are displayed right now, showing the other leagues is a planned feature 😃

**Comment by pjockey** [comment]
Last login: Sun Jun 13 16:11:52 on ttys003
scott@Scotts-MacBook-Pro ~ % ssh pi@192.168.1.175 -p42
pi@192.168.1.175's password: 
Linux raspberrypi 5.10.17+ #1403 Mon Feb 22 11:26:13 GMT 2021 armv6l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Sat Jun 12 11:55:44 2021 from 192.168.1.192
pi@raspberrypi:~ $ cd led-board-manager/
pi@raspberrypi:~/led-board-manager $ ls
api         README.md                      testing
assets      requirements.txt               tests
Capstone    sample.supervisor-daemon.conf  TODO.txt
db.sqlite3  scoreboard                     VERSION
env         scripts                        webgui-log.out
LICENSE     staticfiles
manage.py   supervisor-daemon.conf
pi@raspberrypi:~/led-board-manager $ nano supervisor-daemon.conf














```
  GNU nano 3.2                     supervisor-daemon.conf                                

[program:led-board-manager]
command=/home/pi/led-board-manager/env/bin/gunicorn Capstone.wsgi -b 0:9002
directory=/home/pi/led-board-manager
user=pi
stopasgroup=true
stderr_logfile=/var/log/scoreboard-webgui.stderr.log
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=10
stdout_logfile=/var/log/scoreboard-webgui.stdout.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=10


[program:MLBscoreboard]
command=sudo python2 ./main.py --led-rows=32 --led-cols=64 --led-brightness=80 --led-gpi$
directory=/home/pi/mlb-led-scoreboard
autostart=false
autorestart=true
stderr_logfile=/var/log/MLBscoreboard.stderr.log
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=10
stdout_logfile=/var/log/MLBscoreboard.stdout.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=10


[program:NFLscoreboard]
command=sudo python2 ./main.py --led-rows=32 --led-cols=64 --led-brightness=80 --led-gpi$
directory=/home/pi/nfl-led-scoreboard
autostart=false
autorestart=true
stderr_logfile=/var/log/NHLscoreboard.stderr.log
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=10
stdout_logfile=/var/log/NHLscoreboard.stdout.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=10

[group:boards]
programs=MLBscoreboard,NFLscoreboard,scoreboard
```

```
pi@raspberrypi:~/led-board-manager $ sudo supervisorctl reread && sudo supervisorctl update all
No config updates to processes
pi@raspberrypi:~/led-board-manager $
```

```
pi@raspberrypi:~/led-board-manager $ cat /var/log/supervisord.log
cat: /var/log/supervisord.log: No such file or directory
pi@raspberrypi:~/led-board-manager $ 
```

**Comment by sflems** [comment]
> 
> 
> ```
>   GNU nano 3.2                     supervisor-daemon.conf                                
> 
> [program:led-board-manager]
> command=/home/pi/led-board-manager/env/bin/gunicorn Capstone.wsgi -b 0:9002
> directory=/home/pi/led-board-manager
> user=pi
> stopasgroup=true
> stderr_logfile=/var/log/scoreboard-webgui.stderr.log
> stderr_logfile_maxbytes=1MB
> stderr_logfile_backups=10
> stdout_logfile=/var/log/scoreboard-webgui.stdout.log
> stdout_logfile_maxbytes=1MB
> stdout_logfile_backups=10
> 
> 
> [program:MLBscoreboard]
> command=sudo python2 ./main.py --led-rows=32 --led-cols=64 --led-brightness=80 --led-gpi$
> directory=/home/pi/mlb-led-scoreboard
> autostart=false
> autorestart=true
> stderr_logfile=/var/log/MLBscoreboard.stderr.log
> stderr_logfile_maxbytes=1MB
> stderr_logfile_backups=10
> stdout_logfile=/var/log/MLBscoreboard.stdout.log
> stdout_logfile_maxbytes=1MB
> stdout_logfile_backups=10
> 
> 
> [program:NFLscoreboard]
> command=sudo python2 ./main.py --led-rows=32 --led-cols=64 --led-brightness=80 --led-gpi$
> directory=/home/pi/nfl-led-scoreboard
> autostart=false
> autorestart=true
> stderr_logfile=/var/log/NHLscoreboard.stderr.log
> stderr_logfile_maxbytes=1MB
> stderr_logfile_backups=10
> stdout_logfile=/var/log/NHLscoreboard.stdout.log
> stdout_logfile_maxbytes=1MB
> stdout_logfile_backups=10
> 
> [group:boards]
> programs=MLBscoreboard,NFLscoreboard,scoreboard
> ```

It appears that the template hasn't generated correctly or is missing the scoreboard (NHL) configuration for some reason. The MLB and NFL are there, but the NFL looks mixed with the NHL section.

If you save the NHL boardType in the admin panel, or change any of the constance settings, it will regenerate the conf file again. Follow this with a reread and update all again to be sure and you _should_ be rolling.

**Comment by pjockey** [comment]
I went back into the website and poked around the Admin section, but did not change anything. I then re-did the update procedure. I run the commands you suggested in post #6. The scoreboard commands are there now. 

What I have found is, everytime I run the system  and go onto the website, it changes my MLB config.json to show just this "{}". The complete file has been over written.

**Comment by sflems** [comment]
Sounds like we're almost there! I will look into the bug not allowing you to edit the JSON from the dash. In the meantime, I just confirmed you can edit the profile manually in the admin panel. It should save for you. This is happening because there is no schema found for the board. I'll look into the dash bug.

There are 2 schema files included with the automatic install method. The following commands will copy them over for you and you should notice a nice form being generated.

MLB
```
cp ~/led-board-manager/scoreboard/static/schema/mlb.config.schema.json ~/mlb-led-scoreboard/config.schema.json
```

NFL
```
cp ~/led-board-manager/scoreboard/static/schema/nfl.config.schema.json ~/nfl-led-scoreboard/config.schema.json
```

**Comment by pjockey** [comment]
```
source env/bin/activate && gunicorn Capstone.wsgi -b 192.168.1.175:9002
[2021-06-14 20:40:46 -0600] [1841] [INFO] Starting gunicorn 20.0.4
[2021-06-14 20:40:46 -0600] [1841] [INFO] Listening at: http://192.168.1.175:9002 (1841)
[2021-06-14 20:40:46 -0600] [1841] [INFO] Using worker: sync
[2021-06-14 20:40:46 -0600] [1844] [INFO] Booting worker with pid: 1844
boards:NHLScoreboard: ERROR (no such process)
boards:NHLScoreboard: ERROR (no such process)
Unable to start scoreboard process.
Bad Request: /command
Bad Request: /command
data must contain ['preferred', 'news_ticker', 'standings', 'rotation', 'weather', 'time_format', 'end_of_day', 'full_team_names', 'scrolling_speed', 'debug', 'demo_date'] properties
Traceback (most recent call last):
  File "/home/pi/led-board-manager/scoreboard/models.py", line 191, in pre_save
    instance.full_clean()
  File "/home/pi/led-board-manager/env/lib/python3.7/site-packages/django/db/models/base.py", line 1216, in full_clean
    self.clean()
  File "/home/pi/led-board-manager/scoreboard/models.py", line 171, in clean
    fastjsonschema.validate(self.boardType.schema(), self.config)
  File "/home/pi/led-board-manager/env/lib/python3.7/site-packages/fastjsonschema/__init__.py", line 113, in validate
    return compile(definition, handlers, formats, use_default)(data)
  File "<string>", line 10, in validate_https___github_com_sflems_led_board_manager_staticfiles_schema_mlb_config_schema_json
fastjsonschema.exceptions.JsonSchemaValueException: data must contain ['preferred', 'news_ticker', 'standings', 'rotation', 'weather', 'time_format', 'end_of_day', 'full_team_names', 'scrolling_speed', 'debug', 'demo_date'] properties
["data must contain ['preferred', 'news_ticker', 'standings', 'rotation', 'weather', 'time_format', 'end_of_day', 'full_team_names', 'scrolling_speed', 'debug', 'demo_date'] properties"]
Not Found: /profiles/4
Not Found: /profiles/4
data must contain ['preferred', 'news_ticker', 'standings', 'rotation', 'weather', 'time_format', 'end_of_day', 'full_team_names', 'scrolling_speed', 'debug', 'demo_date'] properties
Traceback (most recent call last):
  File "/home/pi/led-board-manager/scoreboard/models.py", line 191, in pre_save
    instance.full_clean()
  File "/home/pi/led-board-manager/env/lib/python3.7/site-packages/django/db/models/base.py", line 1216, in full_clean
    self.clean()
  File "/home/pi/led-board-manager/scoreboard/models.py", line 171, in clean
    fastjsonschema.validate(self.boardType.schema(), self.config)
  File "/home/pi/led-board-manager/env/lib/python3.7/site-packages/fastjsonschema/__init__.py", line 113, in validate
    return compile(definition, handlers, formats, use_default)(data)
  File "<string>", line 10, in validate_https___github_com_sflems_led_board_manager_staticfiles_schema_mlb_config_schema_json
fastjsonschema.exceptions.JsonSchemaValueException: data must contain ['preferred', 'news_ticker', 'standings', 'rotation', 'weather', 'time_format', 'end_of_day', 'full_team_names', 'scrolling_speed', 'debug', 'demo_date'] properties
["data must contain ['preferred', 'news_ticker', 'standings', 'rotation', 'weather', 'time_format', 'end_of_day', 'full_team_names', 'scrolling_speed', 'debug', 'demo_date'] properties"]
Not Found: /profiles/4
Not Found: /profiles/4
```

**Comment by pjockey** [comment]
<img width="1211" alt="Screen Shot 2021-06-14 at 20 45 04" src="https://user-images.githubusercontent.com/1387701/121985150-73932400-cd51-11eb-9992-0d0dc2386619.png">

**Comment by sflems** [comment]
Could you post the MLB config you are using?

**Comment by pjockey** [comment]
MLB config,json
```
{
	"preferred": {
		"teams": ["Blue Jays"],
		"divisions": ["AL East"]
	},
	"news_ticker": {
		"team_offday": true,
		"always_display": false,
		"preferred_teams": true,
		"traderumors": true,
		"mlb_news": true,
		"countdowns": true,
		"date": true,
		"date_format": "%A, %B %-d"
	},
	"standings": {
		"team_offday": true,
		"mlb_offday": true,
		"always_display": false
	},
	"rotation": {
		"enabled": true,
		"scroll_until_finished": true,
		"only_preferred": false,
		"rates": {
			"live": 15.0,
			"final": 15.0,
			"pregame": 15.0
		},
		"while_preferred_team_live": {
			"enabled": false,
			"during_inning_breaks": false
		}
	},
	"weather": {
		"apikey": "e........",
		"location": "Cranbrook, CA",
		"metric_units": true
	},
	"time_format": "24h",
	"end_of_day": "00:00",
	"full_team_names": true,
	"scrolling_speed": 2,
	"debug": false,
	"demo_date": false
}
```

**Comment by sflems** [comment]
Looks like the schema doesnt like my demo_date definition. I'll have to make an update for it. In the mean time an empty string in demo date will work for now 👍

```
{
	"preferred": {
		"teams": ["Blue Jays"],
		"divisions": ["AL East"]
	},
	"news_ticker": {
		"team_offday": true,
		"always_display": false,
		"preferred_teams": true,
		"traderumors": true,
		"mlb_news": true,
		"countdowns": true,
		"date": true,
		"date_format": "%A, %B %-d"
	},
	"standings": {
		"team_offday": true,
		"mlb_offday": true,
		"always_display": false
	},
	"rotation": {
		"enabled": true,
		"scroll_until_finished": true,
		"only_preferred": false,
		"rates": {
			"live": 15.0,
			"final": 15.0,
			"pregame": 15.0
		},
		"while_preferred_team_live": {
			"enabled": false,
			"during_inning_breaks": false
		}
	},
	"weather": {
		"apikey": "e........",
		"location": "Cranbrook, CA",
		"metric_units": true
	},
	"time_format": "24h",
	"end_of_day": "00:00",
	"full_team_names": true,
	"scrolling_speed": 2,
	"debug": false,
	"demo_date": ""
}
```

**Comment by sflems** [comment]
Just wanted to follow up to see how things were progressing.

The next update will remove the Edit JSON button from the dash, but you will still have the ability manually edit the JSON in the admin panel if needed.
