### ISSUE TITLE
Issue when creating NHL profile

### ISSUE THREAD

**Issue by andrewonice** [sflems/led-board-manager#20]
Hello, first of all thank you for creating this, it is really awesome!

I am having an issue creating an NHL profile. I get the following error each time I try:

"Warning. (['data.sbio.screensaver.start must match pattern ([01]?[0-9]|2[0-3]):[0-5][0-9]'])" and it doesn't save. I can only use the default profile for hockey and can't edit any of the configs. 

I have screensaver set to "false".

**Comment by sflems** [comment]
Glad you're enjoying it! 

I believe the issue/bug lies in that the schema currently is looking for a 24hr time. There are 2 options for a hotfix:

1) Try converting your start and stop time to 24hr time and it should validate.

2) Copy the schema to your config directory from my pending PR on the NHL scoreboard. 

Once this is merged both 00:00 and 12:00 AM formats should work. 🤘

Let me.know if that works out for you. Cheers!

**Comment by andrewonice** [comment]
Thanks, I switched to 24 hour time and received the same error. I managed to get around it by putting 23:59 in both the start and end time. It seems to be looking for a start and end time even when it's set to false.

**Comment by sflems** [comment]
Roger, roger. That makes sense. I'll see if I can add a dependency check next time I'm in there 👌 Thanks for bring this up.

**Comment by sflems** [comment]
I just wanted to add that if you choose to test run the updated schema and a value is missing from a config POST request, they will be set to the default values found in the schema. This should prevent that error entirely and ensures both a start and stop time are present.

Adding dependencies unfortunately breaks the New Profile forms as they do not load the conditional requirements with AJAX correctly. It can work, but I am thinking of implementing a different form system in the near future so this should be an adequate fix in the meantime.

Cheers!

See PR for reference:
https://github.com/riffnshred/nhl-led-scoreboard/pull/293

**Comment by sflems** [comment]
Schemas have been update, will close this issue for now. Cheers!
