### ISSUE TITLE
Looking for Clarification

### ISSUE THREAD

**Issue by Bradw-17** [sflems/led-board-manager#22]
First I just wanted to say thanks for making this project, it seems like it will be a great addition to the NHL LED Scoreboard.

I am just trying to figure out the exact process I need to follow to properly install.

So I installed the nhl-led-scoreboard, got everything up and running properly. 

Then I SSH'd into the scoreboard and started with:
 ```
git clone --recursive https://github.com/sflems/led-board-manager.git
cd led-board-manager
```

And since the nhl-led-scoreboard has Supervisor running already, I followed option 1 of the "Auto-start server". After this however, I am a little unclear on where to go forward. 

I have tried  a couple of different routes without much success.  I guess I just need clarification where to start again after that first autostart option.

**Comment by sflems** [comment]
It looks like I've jumbled up the readme a bit. Once you've modified the Includes in the supervisor configuration, you can return to the steps below:


```sudo apt install python3-venv
python3 -m venv env
./scripts/install.sh
sudo supervisorctl reread && sudo supervisorctl reload```

Once finished, you should be able to start the server with:

```sudo supervisorctl start led-board-manager```

Let me know if that gets it rolling for you and I'll get to updating the instructions. Cheers!

**Comment by sflems** [comment]
Readme has been updated for clarification. Feel free to reopen the issue or reach out if you are still having troubles. Cheers!
