### ISSUE TITLE
Default Password

### ISSUE THREAD

**Issue by stickyricebandit** [sflems/led-board-manager#23]
I can't access using the default password no matter what I do. I've reinstalled probably 4 times and I can't get logged in.

I did add the IP address to allow cookies.

**Comment by sflems** [comment]
Did you follow the automatic or manual install? Usually this happens if the teams/admin data isn't loaded. You can run the following to import them and should be able to login.

```
python3 manage.py makemigrations
python3 manage.py migrate
python3 manage.py loaddata teams.json
python3 manage.py test
```

If it throws some errors, feel free to share them here. Cheers!
